config/routes.rb
Rails.application.routes.draw do
	post 'search', to: 'posts#search'
  resources :posts
  get 'blog', to: 'posts#index', as: 'blog'
  get 'posts', to: redirect('/blog')
  root 'pages#home'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
	has_rich_text :summary
	has_rich_text :body

	def self.search input
		@posts = where("title LIKE ?", "%#{input}%")
		@posts += Post.joins("INNER JOIN action_text_rich_texts ON action_text_rich_texts.record_id = posts.id").where("action_text_rich_texts.body LIKE ?", "%#{input}%")
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  	@disable_nav = true
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    if params[:search]
      @posts = Post.search(params[:search])
      puts "#"
      puts "#"
      puts "#"
      puts "#"
      puts @posts.count
    else
      @posts = Post.all
    end
    @posts = @posts.uniq.sort_by(&:created_at).reverse

    respond_to do |format|
      format.js { render partial: "index" }
      format.html {}
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :summary, :search)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/_navbar.html.erb
<div class="navbar shadow-sm fixed-top" id="navbar">
	<div class="navbar-brand">
		<h3><%= link_to 'Dean', root_path, class:'navbar-brand-link' %></h3>
	</div>
		<div class="navbar-links-container">
			<ul class="navbar-links">
				<li class="navbar-link-item"><%= link_to "Portfolio", '#', class:'navbar-link' %>
				</li>
				<li class="navbar-link-item"><%= link_to "Resume", '#', class:'navbar-link' %>
				</li>
				<li class="navbar-link-item <%= request.fullpath == blog_path ? 'navbar-link-active' : '' %>"> 
					<%= link_to "Blog", blog_path, class:'navbar-link' %>
				</li>
			</ul>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' unless @disable_nav %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="home-wrapper">
	<div class="float-left home-link-container">
		<h1 class="home-portfolio-link"><%= link_to 'portfolio', '#', class:'home-link' %></h1>
		<h1 class="home-resume-link"><%= link_to 'resume', '#', class:'home-link' %></h1>
		<h1 class="home-blog-link"><%= link_to 'blog', blog_path, class:'home-link' %></h1>

	</div>
</div>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :summary %>
    <%= form.rich_text_area :summary %>
  </div>

    <div class="field">
    <%= form.label :body %>
    <%= form.rich_text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_index.js.erb
$('#blog-wrapper').html("<%= j render @posts %>")

app/views/posts/_post.html.erb
<div class="container shadow blog-container" id="post_<%= post.id %>">
  <h2 class=""><%= link_to post.title, post, class:'blog-title' %></h1>
  <h6 class="blog-subtitle"><%= post.created_at.strftime("%b %e, %Y")%>
  </h6>
  <hr class="blog-subtitle-bar float-left">
  <br>
  <div class="blog-summary">
    <%= post.summary %>
  </div>
  <div class="float-right">
    <%= link_to "Read More", post, class:'btn btn-light blog-button' %>
  </div>
  <hr>
</div>

app/views/posts/edit.html.erb
<div class="blog-wrapper">
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>
</div>

app/views/posts/index.html.erb
<div class="container">
  <div class="search-container float-right">
    <%= form_tag(blog_path, method: :get, remote: true, id: 'search_form') do %>
      <div class="input-group mb-3">
        <%= text_field_tag :search, params[:search], class:'form-control', onKeyUp: 'submitFromAjax()' %>
        <div class="input-group-append">
          <%= submit_tag 'Search', class:'btn btn-outline-secondary' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<div class="blog-wrapper" id="blog-wrapper">
  <% @posts.each do |post| %>
    <%= render post %>
  <% end %>
</div>

<script>
function submitFromAjax(){
   var request =  $.ajax({
                   type: "get",
                   url : "/blog",
                   dataType: "script",
                   data : {search: $("#search_form #search").val()}
                  });
                   request.done(function(data) {
                   });
                   request.fail(function(jqXHR, textStatus) {
                   });
}
</script>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div class="blog-wrapper">
	<div class="container shadow blog-container">
		<h1 class="text-center"><%= link_to @post.title, blog_path, class:'blog-title' %></h1>
		<h6 class="text-center">Posted by @author <%= @post.created_at.strftime("at %I:%M %p on %b %e, %Y") %>
		</h6>
		<hr>

		<div class="text-justify blog-body">
			<%= @post.body %>
		</div>
	</div>
</div>